using System.Globalization;
using DevSpaceStatusPet.Models;

namespace DevSpaceStatusPet.Services;

public enum UiLanguage
{
    Japanese,
    English,
    ChineseSimplified
}

public sealed class Localizer
{
    private readonly Func<AppSettings> _settingsProvider;

    public Localizer(Func<AppSettings> settingsProvider)
    {
        _settingsProvider = settingsProvider;
    }

    public UiLanguage Language => Resolve(_settingsProvider().LanguagePreference);

    public string this[string key] => Get(key);

    public string Get(string key, params object[] args)
    {
        var catalog = Language switch
        {
            UiLanguage.Japanese => Japanese,
            UiLanguage.ChineseSimplified => ChineseSimplified,
            _ => English
        };
        var text = catalog.TryGetValue(key, out var value)
            ? value
            : English.TryGetValue(key, out var fallback) ? fallback : key;
        return args.Length == 0
            ? text
            : string.Format(CultureInfo.CurrentCulture, text, args);
    }

    public string State(ActivityState state) => state switch
    {
        ActivityState.Working => Get("Working"),
        ActivityState.Waiting => Get("Waiting"),
        ActivityState.Failed => Get("Failed"),
        ActivityState.Stalled => Get("Stalled"),
        ActivityState.Stopped => Get("Stopped"),
        _ => Get("Idle")
    };

    public string Operation(OperationKind kind, string? detail) => kind switch
    {
        OperationKind.Read => string.IsNullOrWhiteSpace(detail) ? Get("ReadFile") : Get("ReadTarget", detail),
        OperationKind.Edit => string.IsNullOrWhiteSpace(detail) ? Get("EditFile") : Get("EditTarget", detail),
        OperationKind.Write => string.IsNullOrWhiteSpace(detail) ? Get("WriteFile") : Get("WriteTarget", detail),
        OperationKind.Command => string.IsNullOrWhiteSpace(detail) ? Get("RunCommand") : Get("CommandTarget", detail),
        OperationKind.OpenWorkspace => Get("OpenWorkspace"),
        OperationKind.Dotnet => string.IsNullOrWhiteSpace(detail) ? "dotnet" : detail,
        OperationKind.Git => string.IsNullOrWhiteSpace(detail) ? "git" : detail,
        OperationKind.Ffmpeg => string.IsNullOrWhiteSpace(detail) ? "ffmpeg" : detail,
        OperationKind.PowerShell => "PowerShell",
        OperationKind.Python => "Python",
        OperationKind.LocalProcess => string.IsNullOrWhiteSpace(detail) ? Get("LocalProcess") : detail,
        OperationKind.Stopped => Get("Stopped"),
        OperationKind.Idle => Get("Idle"),
        _ => string.IsNullOrWhiteSpace(detail) ? Get("Unknown") : detail
    };

    public static UiLanguage Resolve(UiLanguagePreference preference) => preference switch
    {
        UiLanguagePreference.Japanese => UiLanguage.Japanese,
        UiLanguagePreference.English => UiLanguage.English,
        UiLanguagePreference.ChineseSimplified => UiLanguage.ChineseSimplified,
        _ => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName switch
        {
            "ja" => UiLanguage.Japanese,
            "zh" => UiLanguage.ChineseSimplified,
            _ => UiLanguage.English
        }
    };

    private static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string>
    {
        ["AppName"] = "DevSpace Status Pet",
        ["Working"] = "作業中",
        ["Waiting"] = "次の処理待ち",
        ["Failed"] = "処理失敗",
        ["Stalled"] = "停滞の疑い",
        ["Stopped"] = "停止中",
        ["Idle"] = "待機中",
        ["Unknown"] = "不明",
        ["ReadFile"] = "ファイル読取",
        ["ReadTarget"] = "読取: {0}",
        ["EditFile"] = "ファイル編集",
        ["EditTarget"] = "編集: {0}",
        ["WriteFile"] = "ファイル作成",
        ["WriteTarget"] = "作成: {0}",
        ["RunCommand"] = "コマンド実行",
        ["CommandTarget"] = "コマンド: {0}",
        ["OpenWorkspace"] = "ワークスペースを開く",
        ["LocalProcess"] = "ローカル処理",
        ["Project"] = "プロジェクト: {0}",
        ["Operation"] = "処理: {0}",
        ["Elapsed"] = "経過時間: {0}",
        ["Refresh"] = "今すぐ再確認",
        ["ShowRecoverPet"] = "ペットを表示／復旧",
        ["Settings"] = "設定",
        ["OpenLog"] = "ログを開く",
        ["OpenFolder"] = ".devspaceフォルダーを開く",
        ["Exit"] = "終了",
        ["ShowBubble"] = "吹き出しを常時表示",
        ["Theme"] = "ロボットテーマ",
        ["Classic"] = "クラシック（状態色）",
        ["Neon"] = "ネオン（紫・黄）",
        ["BubbleTheme"] = "吹き出しテーマ",
        ["BubbleLight"] = "ライト",
        ["BubbleDark"] = "ダーク",
        ["BubbleStyle"] = "吹き出しデザイン",
        ["BubbleSpeech"] = "標準吹き出し",
        ["BubbleMonitorCardNeon"] = "モニターカード（ネオン）",
        ["BubbleMonitorCardClean"] = "モニターカード（クリーン）",
        ["Language"] = "言語 / Language",
        ["Auto"] = "自動（OS言語）",
        ["Japanese"] = "日本語",
        ["English"] = "English",
        ["ChineseSimplified"] = "简体中文",
        ["ResetPosition"] = "位置を右下へ戻す",
        ["HideAtEdge"] = "画面端に隠す",
        ["RestoreFromEdge"] = "画面端から戻す",
        ["ParallelMore"] = "+{0}件",
        ["OtherTasks"] = "ほかの処理",
        ["WorkDoneTitle"] = "DevSpace 作業区切り完了",
        ["WorkFailedTitle"] = "DevSpace 作業失敗",
        ["WorkTime"] = "作業時間: {0}",
        ["StopTitle"] = "DevSpace 停止",
        ["StopText"] = "DevSpaceサーバーが停止しました。",
        ["StallTitle"] = "DevSpace 停滞の疑い",
        ["Status"] = "状態: {0}",
        ["Port"] = "ポート: {0}",
        ["Config"] = "設定ファイル: {0}",
        ["Log"] = "ログ: {0}",
        ["General"] = "一般",
        ["Appearance"] = "表示",
        ["Notification"] = "通知",
        ["Scale"] = "サイズ",
        ["Opacity"] = "透明度",
        ["QuietSeconds"] = "完了通知までの待機秒数",
        ["StallMinutes"] = "停滞判定（分）",
        ["MaxBubbles"] = "最大吹き出し数",
        ["NotificationsEnabled"] = "Windows通知を有効にする",
        ["StartWithWindows"] = "Windowsログイン時に起動",
        ["Save"] = "保存",
        ["Close"] = "閉じる",
        ["OpenLogFolder"] = "ログフォルダーを開く",
        ["InstallUpdate"] = "インストール／更新",
        ["UninstallV2"] = "アンインストール",
        ["ConfirmUninstall"] = "DevSpace Status Petをアンインストールしますか？\n設定は保持されます。",
        ["InstalledMessage"] = "DevSpace Status Petをインストールしました。\n\n{0}",
        ["UninstallingMessage"] = "DevSpace Status Petをアンインストールします。",
        ["ApplicationError"] = "DevSpace Status Petでエラーが発生しました。\n\n{0}\n\n{1}",
        ["StartupError"] = "DevSpace Status Petを起動できませんでした。\n\n{0}\n\n{1}",
        ["Version"] = "バージョン: {0}",
        ["Saved"] = "設定を保存しました。",
        ["NoLog"] = "ログファイルが見つかりません。",
        ["CheckUpdates"] = "更新を確認",
        ["CheckingUpdates"] = "更新を確認中…",
        ["UpdateAvailableMenu"] = "更新あり: v{0}",
        ["UpdateAvailableTitle"] = "新しいバージョンがあります",
        ["UpdateAvailableText"] = "DevSpace Status Pet v{0}を利用できます。",
        ["UpdateVersionLine"] = "現在: v{0}    最新: v{1}",
        ["UpdatePublished"] = "公開日時: {0}",
        ["NoReleaseNotes"] = "リリースノートはありません。",
        ["UpdateReady"] = "内容を確認してから更新してください。",
        ["InstallUpdateNow"] = "更新する",
        ["OpenReleasePage"] = "GitHubで見る",
        ["Cancel"] = "キャンセル",
        ["DownloadingChecksum"] = "チェックサムを取得しています…",
        ["DownloadingUpdate"] = "更新をダウンロードしています… {0}",
        ["VerifyingUpdate"] = "SHA-256を検証しています…",
        ["ExtractingUpdate"] = "更新を展開しています…",
        ["StartingInstaller"] = "更新版を起動しています…",
        ["UpdateCancelled"] = "更新をキャンセルしました。",
        ["UpdateFailed"] = "更新に失敗しました。",
        ["UpdateFailedDetail"] = "更新に失敗しました。現在のバージョンは変更されていません。\n\n{0}",
        ["UpToDate"] = "最新バージョンです。",
        ["UpdateCheckFailed"] = "更新確認に失敗しました。",
        ["UpdateCheckFailedDetail"] = "更新確認に失敗しました。\n\n{0}",
        ["LatestVersion"] = "最新バージョン",
        ["UpdateStatus"] = "更新状態",
        ["CheckUpdatesOnStartup"] = "起動時に更新を確認",
        ["IncludePrereleaseUpdates"] = "開発版（Prerelease）も確認",
        ["NotChecked"] = "未確認",
        ["None"] = "なし"
    };

    internal static bool HasCompleteCatalogs =>
        CatalogMatches(English, Japanese) && CatalogMatches(English, ChineseSimplified);

    private static bool CatalogMatches(
        IReadOnlyDictionary<string, string> expected,
        IReadOnlyDictionary<string, string> candidate) =>
        expected.Count == candidate.Count && expected.Keys.All(candidate.ContainsKey);

    private static readonly IReadOnlyDictionary<string, string> ChineseSimplified = new Dictionary<string, string>
    {
        ["AppName"] = "DevSpace Status Pet",
        ["Working"] = "工作中",
        ["Waiting"] = "等待下一步",
        ["Failed"] = "处理失败",
        ["Stalled"] = "可能已停滞",
        ["Stopped"] = "已停止",
        ["Idle"] = "空闲",
        ["Unknown"] = "未知",
        ["ReadFile"] = "读取文件",
        ["ReadTarget"] = "读取：{0}",
        ["EditFile"] = "编辑文件",
        ["EditTarget"] = "编辑：{0}",
        ["WriteFile"] = "写入文件",
        ["WriteTarget"] = "写入：{0}",
        ["RunCommand"] = "运行命令",
        ["CommandTarget"] = "命令：{0}",
        ["OpenWorkspace"] = "打开工作区",
        ["LocalProcess"] = "本地进程",
        ["Project"] = "项目：{0}",
        ["Operation"] = "操作：{0}",
        ["Elapsed"] = "已用时间：{0}",
        ["Refresh"] = "立即刷新",
        ["ShowRecoverPet"] = "显示／恢复宠物",
        ["Settings"] = "设置",
        ["OpenLog"] = "打开日志",
        ["OpenFolder"] = "打开 .devspace 文件夹",
        ["Exit"] = "退出",
        ["ShowBubble"] = "始终显示气泡",
        ["Theme"] = "机器人主题",
        ["Classic"] = "经典（状态颜色）",
        ["Neon"] = "霓虹（紫色和黄色）",
        ["BubbleTheme"] = "气泡主题",
        ["BubbleLight"] = "浅色",
        ["BubbleDark"] = "深色",
        ["BubbleStyle"] = "气泡样式",
        ["BubbleSpeech"] = "标准对话气泡",
        ["BubbleMonitorCardNeon"] = "监视卡片（霓虹）",
        ["BubbleMonitorCardClean"] = "监视卡片（简洁）",
        ["Language"] = "语言 / Language",
        ["Auto"] = "自动（系统语言）",
        ["Japanese"] = "日本語",
        ["English"] = "English",
        ["ChineseSimplified"] = "简体中文",
        ["ResetPosition"] = "将位置重置到右下角",
        ["HideAtEdge"] = "隐藏到屏幕边缘",
        ["RestoreFromEdge"] = "从屏幕边缘恢复",
        ["ParallelMore"] = "+{0} 项",
        ["OtherTasks"] = "其他任务",
        ["WorkDoneTitle"] = "DevSpace 工作阶段已完成",
        ["WorkFailedTitle"] = "DevSpace 工作失败",
        ["WorkTime"] = "工作时间：{0}",
        ["StopTitle"] = "DevSpace 已停止",
        ["StopText"] = "DevSpace 服务器已停止。",
        ["StallTitle"] = "DevSpace 可能已停滞",
        ["Status"] = "状态：{0}",
        ["Port"] = "端口：{0}",
        ["Config"] = "配置文件：{0}",
        ["Log"] = "日志：{0}",
        ["General"] = "常规",
        ["Appearance"] = "外观",
        ["Notification"] = "通知",
        ["Scale"] = "大小",
        ["Opacity"] = "透明度",
        ["QuietSeconds"] = "完成通知前的静默秒数",
        ["StallMinutes"] = "停滞阈值（分钟）",
        ["MaxBubbles"] = "最大气泡数",
        ["NotificationsEnabled"] = "启用 Windows 通知",
        ["StartWithWindows"] = "随 Windows 启动",
        ["Save"] = "保存",
        ["Close"] = "关闭",
        ["OpenLogFolder"] = "打开日志文件夹",
        ["InstallUpdate"] = "安装／更新",
        ["UninstallV2"] = "卸载",
        ["ConfirmUninstall"] = "要卸载 DevSpace Status Pet 吗？\n设置将保留。",
        ["InstalledMessage"] = "DevSpace Status Pet 已安装。\n\n{0}",
        ["UninstallingMessage"] = "正在卸载 DevSpace Status Pet。",
        ["ApplicationError"] = "DevSpace Status Pet 遇到错误。\n\n{0}\n\n{1}",
        ["StartupError"] = "DevSpace Status Pet 无法启动。\n\n{0}\n\n{1}",
        ["Version"] = "版本：{0}",
        ["Saved"] = "设置已保存。",
        ["NoLog"] = "找不到日志文件。",
        ["CheckUpdates"] = "检查更新",
        ["CheckingUpdates"] = "正在检查更新…",
        ["UpdateAvailableMenu"] = "有可用更新：v{0}",
        ["UpdateAvailableTitle"] = "有新版本可用",
        ["UpdateAvailableText"] = "DevSpace Status Pet v{0} 可用。",
        ["UpdateVersionLine"] = "当前：v{0}    最新：v{1}",
        ["UpdatePublished"] = "发布时间：{0}",
        ["NoReleaseNotes"] = "没有可用的发行说明。",
        ["UpdateReady"] = "更新前请查看发行说明。",
        ["InstallUpdateNow"] = "立即更新",
        ["OpenReleasePage"] = "在 GitHub 上查看",
        ["Cancel"] = "取消",
        ["DownloadingChecksum"] = "正在下载校验和…",
        ["DownloadingUpdate"] = "正在下载更新… {0}",
        ["VerifyingUpdate"] = "正在验证 SHA-256…",
        ["ExtractingUpdate"] = "正在解压更新…",
        ["StartingInstaller"] = "正在启动更新版本…",
        ["UpdateCancelled"] = "更新已取消。",
        ["UpdateFailed"] = "更新失败。",
        ["UpdateFailedDetail"] = "更新失败。当前版本未被更改。\n\n{0}",
        ["UpToDate"] = "已是最新版本。",
        ["UpdateCheckFailed"] = "检查更新失败。",
        ["UpdateCheckFailedDetail"] = "无法检查更新。\n\n{0}",
        ["LatestVersion"] = "最新版本",
        ["UpdateStatus"] = "更新状态",
        ["CheckUpdatesOnStartup"] = "启动时检查更新",
        ["IncludePrereleaseUpdates"] = "同时检查开发版（Prerelease）",
        ["NotChecked"] = "未检查",
        ["None"] = "无"
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["AppName"] = "DevSpace Status Pet",
        ["Working"] = "Working",
        ["Waiting"] = "Waiting for next step",
        ["Failed"] = "Process failed",
        ["Stalled"] = "Possibly stalled",
        ["Stopped"] = "Stopped",
        ["Idle"] = "Idle",
        ["Unknown"] = "Unknown",
        ["ReadFile"] = "Read file",
        ["ReadTarget"] = "Read: {0}",
        ["EditFile"] = "Edit file",
        ["EditTarget"] = "Edit: {0}",
        ["WriteFile"] = "Write file",
        ["WriteTarget"] = "Write: {0}",
        ["RunCommand"] = "Run command",
        ["CommandTarget"] = "Command: {0}",
        ["OpenWorkspace"] = "Open workspace",
        ["LocalProcess"] = "Local process",
        ["Project"] = "Project: {0}",
        ["Operation"] = "Operation: {0}",
        ["Elapsed"] = "Elapsed: {0}",
        ["Refresh"] = "Refresh now",
        ["ShowRecoverPet"] = "Show / recover pet",
        ["Settings"] = "Settings",
        ["OpenLog"] = "Open log",
        ["OpenFolder"] = "Open .devspace folder",
        ["Exit"] = "Exit",
        ["ShowBubble"] = "Always show bubbles",
        ["Theme"] = "Robot theme",
        ["Classic"] = "Classic (status colors)",
        ["Neon"] = "Neon (purple and yellow)",
        ["BubbleTheme"] = "Bubble theme",
        ["BubbleLight"] = "Light",
        ["BubbleDark"] = "Dark",
        ["BubbleStyle"] = "Bubble design",
        ["BubbleSpeech"] = "Standard speech bubble",
        ["BubbleMonitorCardNeon"] = "Monitor card (Neon)",
        ["BubbleMonitorCardClean"] = "Monitor card (Clean)",
        ["Language"] = "Language / 言語",
        ["Auto"] = "Auto (OS language)",
        ["Japanese"] = "日本語",
        ["English"] = "English",
        ["ChineseSimplified"] = "简体中文",
        ["ResetPosition"] = "Reset position to bottom-right",
        ["HideAtEdge"] = "Hide at screen edge",
        ["RestoreFromEdge"] = "Restore from screen edge",
        ["ParallelMore"] = "+{0} more",
        ["OtherTasks"] = "Other tasks",
        ["WorkDoneTitle"] = "DevSpace work segment finished",
        ["WorkFailedTitle"] = "DevSpace work failed",
        ["WorkTime"] = "Work time: {0}",
        ["StopTitle"] = "DevSpace stopped",
        ["StopText"] = "The DevSpace server has stopped.",
        ["StallTitle"] = "DevSpace may be stalled",
        ["Status"] = "Status: {0}",
        ["Port"] = "Port: {0}",
        ["Config"] = "Config: {0}",
        ["Log"] = "Log: {0}",
        ["General"] = "General",
        ["Appearance"] = "Appearance",
        ["Notification"] = "Notifications",
        ["Scale"] = "Size",
        ["Opacity"] = "Opacity",
        ["QuietSeconds"] = "Quiet seconds before completion notification",
        ["StallMinutes"] = "Stall threshold (minutes)",
        ["MaxBubbles"] = "Maximum bubbles",
        ["NotificationsEnabled"] = "Enable Windows notifications",
        ["StartWithWindows"] = "Start with Windows",
        ["Save"] = "Save",
        ["Close"] = "Close",
        ["OpenLogFolder"] = "Open log folder",
        ["InstallUpdate"] = "Install / update",
        ["UninstallV2"] = "Uninstall",
        ["ConfirmUninstall"] = "Uninstall DevSpace Status Pet?\nSettings will be kept.",
        ["InstalledMessage"] = "DevSpace Status Pet has been installed.\n\n{0}",
        ["UninstallingMessage"] = "DevSpace Status Pet will be uninstalled.",
        ["ApplicationError"] = "DevSpace Status Pet encountered an error.\n\n{0}\n\n{1}",
        ["StartupError"] = "DevSpace Status Pet could not start.\n\n{0}\n\n{1}",
        ["Version"] = "Version: {0}",
        ["Saved"] = "Settings saved.",
        ["NoLog"] = "The log file was not found.",
        ["CheckUpdates"] = "Check for updates",
        ["CheckingUpdates"] = "Checking for updates…",
        ["UpdateAvailableMenu"] = "Update available: v{0}",
        ["UpdateAvailableTitle"] = "A new version is available",
        ["UpdateAvailableText"] = "DevSpace Status Pet v{0} is available.",
        ["UpdateVersionLine"] = "Current: v{0}    Latest: v{1}",
        ["UpdatePublished"] = "Published: {0}",
        ["NoReleaseNotes"] = "No release notes are available.",
        ["UpdateReady"] = "Review the release notes before updating.",
        ["InstallUpdateNow"] = "Update now",
        ["OpenReleasePage"] = "View on GitHub",
        ["Cancel"] = "Cancel",
        ["DownloadingChecksum"] = "Downloading checksum…",
        ["DownloadingUpdate"] = "Downloading update… {0}",
        ["VerifyingUpdate"] = "Verifying SHA-256…",
        ["ExtractingUpdate"] = "Extracting update…",
        ["StartingInstaller"] = "Starting the updated version…",
        ["UpdateCancelled"] = "Update cancelled.",
        ["UpdateFailed"] = "Update failed.",
        ["UpdateFailedDetail"] = "The update failed. Your current version was not changed.\n\n{0}",
        ["UpToDate"] = "You are using the latest version.",
        ["UpdateCheckFailed"] = "Update check failed.",
        ["UpdateCheckFailedDetail"] = "Could not check for updates.\n\n{0}",
        ["LatestVersion"] = "Latest version",
        ["UpdateStatus"] = "Update status",
        ["CheckUpdatesOnStartup"] = "Check for updates at startup",
        ["IncludePrereleaseUpdates"] = "Include prerelease builds",
        ["NotChecked"] = "Not checked",
        ["None"] = "None"
    };
}
